package crossword

// Entry is one answer with its clue. Answers are Indonesian words written in
// capital letters A-Z; clues are bilingual. Key identifies the word in the
// admin-managed bank (built-in words use cw-{level}-{answer}).
type Entry struct {
	Answer string
	ClueID string
	ClueEN string
	Key    string
}

type seedEntry struct{ Answer, ClueID, ClueEN string }

// seed is the bundled bank: the fallback until the first sync from Laravel
// and the source of the admin bank's initial import. Higher levels use
// longer, harder words and clues from secondary school subjects.
var seed = map[int][]seedEntry{
	1: {
		{"SAPI", "Hewan ternak penghasil susu", "Farm animal that gives milk"},
		{"BUKU", "Lembaran kertas berjilid untuk dibaca", "Bound pages you read"},
		{"BOLA", "Benda bulat yang ditendang saat bermain sepak bola", "Round thing kicked in football"},
		{"MATA", "Indra untuk melihat", "Sense organ used to see"},
		{"IKAN", "Hewan air yang bernapas dengan insang", "Water animal that breathes with gills"},
		{"BULAN", "Benda langit yang tampak terang di malam hari", "Bright object in the night sky"},
		{"AYAM", "Unggas yang berkokok di pagi hari", "Bird that crows in the morning"},
		{"PADI", "Tanaman yang menghasilkan beras", "Plant that produces rice"},
		{"HIJAU", "Warna daun yang segar", "Colour of fresh leaves"},
		{"RODA", "Bagian kendaraan yang berputar", "Round part of a vehicle that spins"},
		{"KAKI", "Anggota tubuh untuk berjalan", "Body part used to walk"},
		{"TOPI", "Penutup kepala agar tidak kepanasan", "Head covering against the sun"},
		{"GAJAH", "Hewan besar berbelalai", "Big animal with a trunk"},
		{"SUSU", "Minuman putih dari sapi", "White drink from cows"},
		{"APEL", "Buah merah atau hijau yang renyah", "Crunchy red or green fruit"},
		{"TELUR", "Dihasilkan ayam dan bisa direbus", "Laid by hens, can be boiled"},
		{"AWAN", "Kumpulan uap air putih di langit", "White water vapour in the sky"},
		{"HUJAN", "Air yang turun dari langit", "Water falling from the sky"},
		{"PAGI", "Waktu matahari terbit", "Time when the sun rises"},
		{"LIMA", "Angka setelah empat", "Number after four"},
		{"ROTI", "Makanan dari tepung yang dipanggang", "Baked food made from flour"},
		{"MADU", "Cairan manis yang dibuat lebah", "Sweet liquid made by bees"},
		{"KUDA", "Hewan yang bisa ditunggangi dan berlari kencang", "Fast animal people ride"},
		{"BEBEK", "Unggas yang pandai berenang dan berbunyi kwek", "Bird that swims and quacks"},
		{"JERUK", "Buah oranye yang kaya vitamin C", "Orange fruit rich in vitamin C"},
		{"MEJA", "Perabot untuk menulis atau makan", "Furniture to write or eat on"},
		{"KURSI", "Perabot untuk duduk", "Furniture to sit on"},
		{"GURU", "Orang yang mengajar di sekolah", "Person who teaches at school"},
		{"BINTANG", "Benda langit yang berkelip di malam hari", "Twinkling light in the night sky"},
		{"PELANGI", "Lengkung warna-warni setelah hujan", "Colourful arc after rain"},
		{"TIGA", "Jumlah sisi segitiga", "Number of sides of a triangle"},
		{"SEMUT", "Serangga kecil yang suka gula", "Small insect that loves sugar"},
	},
	2: {
		{"GARUDA", "Burung lambang negara Indonesia", "Bird on Indonesia's coat of arms"},
		{"BATIK", "Kain bermotif warisan budaya Indonesia", "Patterned cloth, Indonesian heritage"},
		{"ANGKLUNG", "Alat musik bambu dari Jawa Barat", "Bamboo instrument from West Java"},
		{"KOMPAS", "Alat penunjuk arah mata angin", "Tool that shows directions"},
		{"KUBUS", "Bangun ruang dengan enam sisi persegi", "Solid with six square faces"},
		{"AKAR", "Bagian tumbuhan yang menyerap air dari tanah", "Plant part that absorbs water from soil"},
		{"MATAHARI", "Bintang pusat tata surya", "Star at the centre of the solar system"},
		{"BUMI", "Planet tempat kita tinggal", "Planet we live on"},
		{"PULAU", "Daratan yang dikelilingi air", "Land surrounded by water"},
		{"SAMUDRA", "Lautan yang sangat luas", "Very large body of salt water"},
		{"MERAPI", "Gunung api aktif di dekat Yogyakarta", "Active volcano near Yogyakarta"},
		{"SAWAH", "Lahan basah tempat menanam padi", "Wet field where rice grows"},
		{"PERSEGI", "Bangun datar dengan empat sisi sama panjang", "Flat shape with four equal sides"},
		{"LINGKARAN", "Bangun datar yang tidak memiliki sudut", "Flat shape with no corners"},
		{"KATAK", "Hewan amfibi yang pandai melompat", "Amphibian that is good at jumping"},
		{"PAUS", "Mamalia laut terbesar", "Largest sea mammal"},
		{"DAUN", "Bagian tumbuhan tempat memasak makanan", "Plant part where food is made"},
		{"KELINCI", "Hewan bertelinga panjang yang suka wortel", "Long-eared animal that likes carrots"},
		{"MERDEKA", "Bebas dari penjajahan", "Free from colonial rule"},
		{"BENDERA", "Kain berwarna lambang suatu negara", "Coloured cloth that represents a country"},
		{"BAMBU", "Tanaman beruas yang dipakai membuat angklung", "Jointed plant used to make angklung"},
		{"KANCIL", "Hewan cerdik dalam dongeng Nusantara", "Clever mouse-deer of Indonesian fables"},
		{"PELABUHAN", "Tempat kapal berlabuh", "Place where ships dock"},
		{"PETANI", "Orang yang bekerja menanam di sawah", "Person who grows crops"},
		{"DOKTER", "Orang yang mengobati orang sakit", "Person who treats the sick"},
		{"TERMOMETER", "Alat untuk mengukur suhu", "Tool to measure temperature"},
		{"PECAHAN", "Bilangan seperti setengah atau sepertiga", "Numbers like a half or a third"},
		{"KALENDER", "Daftar hari, minggu, dan bulan dalam setahun", "List of the days and months of a year"},
		{"RUPIAH", "Mata uang Indonesia", "Indonesia's currency"},
		{"WAYANG", "Boneka kulit dalam pertunjukan dalang", "Shadow puppets used by a dalang"},
		{"SUNGAI", "Aliran air besar dari hulu ke hilir", "Large stream flowing to the sea"},
		{"VITAMIN", "Zat dalam makanan yang menjaga kesehatan", "Nutrient in food that keeps you healthy"},
	},
	3: {
		{"KLOROFIL", "Zat hijau daun untuk fotosintesis", "Green pigment used in photosynthesis"},
		{"OKSIGEN", "Gas yang kita hirup untuk bernapas", "Gas we breathe in"},
		{"GRAVITASI", "Gaya tarik bumi terhadap benda", "Force pulling objects to the earth"},
		{"PROKLAMASI", "Pernyataan kemerdekaan Indonesia tahun 1945", "Indonesia's 1945 declaration of independence"},
		{"MAGNET", "Benda yang dapat menarik besi", "Object that attracts iron"},
		{"DEMOKRASI", "Pemerintahan dari, oleh, dan untuk rakyat", "Government of, by and for the people"},
		{"PRISMA", "Bangun ruang dengan alas dan tutup yang sama", "Solid with two identical end faces"},
		{"MAJAPAHIT", "Kerajaan besar dengan Mahapatih Gajah Mada", "Kingdom whose prime minister was Gajah Mada"},
		{"SRIWIJAYA", "Kerajaan maritim besar di Sumatra", "Great maritime kingdom in Sumatra"},
		{"EKUATOR", "Garis khayal lintang nol derajat", "Imaginary line at zero latitude"},
		{"FOTOSINTESIS", "Proses tumbuhan membuat makanan dengan cahaya", "How plants make food from light"},
		{"KONDENSASI", "Perubahan uap menjadi titik air", "Vapour turning into water droplets"},
		{"PANCASILA", "Dasar negara Indonesia", "Foundation of the Indonesian state"},
		{"VERTEBRATA", "Kelompok hewan bertulang belakang", "Animals with a backbone"},
		{"HERBIVORA", "Hewan pemakan tumbuhan", "Plant-eating animal"},
		{"KARNIVORA", "Hewan pemakan daging", "Meat-eating animal"},
		{"PARAGRAF", "Kumpulan kalimat dengan satu gagasan utama", "Group of sentences with one main idea"},
		{"SINONIM", "Kata yang maknanya sama", "Word with the same meaning"},
		{"ANTONIM", "Kata yang maknanya berlawanan", "Word with the opposite meaning"},
		{"KOPERASI", "Badan usaha berasas kekeluargaan", "Business run on mutual help"},
		{"DIAMETER", "Garis tengah lingkaran", "Line across a circle through its centre"},
		{"STATISTIKA", "Ilmu mengumpulkan dan mengolah data", "Science of collecting and analysing data"},
		{"ATMOSFER", "Lapisan udara yang menyelimuti bumi", "Layer of air around the earth"},
		{"EROSI", "Pengikisan tanah oleh air atau angin", "Soil worn away by water or wind"},
		{"KOMET", "Benda langit berekor yang mengelilingi matahari", "Icy object with a tail orbiting the sun"},
		{"PROTEIN", "Zat gizi pembangun tubuh", "Nutrient that builds the body"},
		{"MUSYAWARAH", "Berunding untuk mencapai mufakat", "Discussing to reach consensus"},
		{"NOVEL", "Karangan prosa panjang berisi cerita", "Long work of fiction"},
		{"PROVINSI", "Wilayah administrasi di bawah negara", "Region directly under the national government"},
		{"EKSPOR", "Menjual barang ke luar negeri", "Selling goods abroad"},
		{"IMPOR", "Membeli barang dari luar negeri", "Buying goods from abroad"},
		{"ALGORITMA", "Langkah-langkah logis untuk menyelesaikan masalah", "Step-by-step method to solve a problem"},
	},
	4: {
		{"MITOKONDRIA", "Organel tempat respirasi sel", "Organelle where cells respire"},
		{"HIPOTENUSA", "Sisi miring segitiga siku-siku", "Longest side of a right triangle"},
		{"LOGARITMA", "Kebalikan dari operasi perpangkatan", "Inverse operation of exponentiation"},
		{"EKOSISTEM", "Hubungan timbal balik makhluk hidup dan lingkungannya", "Living things interacting with their environment"},
		{"INFLASI", "Kenaikan harga barang secara umum dan terus-menerus", "General, ongoing rise in prices"},
		{"KONDUKTOR", "Bahan yang mudah menghantarkan listrik", "Material that conducts electricity well"},
		{"ELEKTRON", "Partikel bermuatan negatif dalam atom", "Negatively charged particle in an atom"},
		{"KHATULISTIWA", "Nama lain garis ekuator", "Another name for the equator"},
		{"PARLEMEN", "Lembaga perwakilan rakyat", "Body of elected representatives"},
		{"EVAPORASI", "Penguapan air karena panas", "Water turning into vapour by heat"},
		{"OSMOSIS", "Perpindahan air melalui membran semipermeabel", "Water moving through a semipermeable membrane"},
		{"ENZIM", "Protein yang mempercepat reaksi kimia di tubuh", "Protein that speeds up reactions in the body"},
		{"GLOBALISASI", "Proses mendunia yang menghubungkan antarnegara", "Process connecting countries worldwide"},
		{"REFORMASI", "Gerakan perubahan politik Indonesia tahun 1998", "Indonesia's 1998 political reform movement"},
		{"KATALIS", "Zat yang mempercepat reaksi tanpa ikut berubah", "Substance that speeds up a reaction unchanged"},
		{"MOLEKUL", "Gabungan dua atom atau lebih", "Two or more atoms bonded together"},
		{"KROMOSOM", "Pembawa sifat keturunan di inti sel", "Carrier of genes in the cell nucleus"},
		{"TRIGONOMETRI", "Cabang matematika tentang sudut dan segitiga", "Maths of angles and triangles"},
		{"INTEGRAL", "Kebalikan dari turunan dalam kalkulus", "Inverse of the derivative in calculus"},
		{"RESONANSI", "Ikut bergetarnya benda karena frekuensi yang sama", "Vibration caused by a matching frequency"},
		{"IONOSFER", "Lapisan atmosfer yang memantulkan gelombang radio", "Atmosphere layer that reflects radio waves"},
		{"FEODALISME", "Sistem sosial berdasarkan kepemilikan tanah bangsawan", "Social system based on noble landholding"},
		{"MONOPOLI", "Pasar yang dikuasai satu penjual", "Market controlled by one seller"},
		{"SUBSIDI", "Bantuan dana pemerintah untuk menekan harga", "Government aid to keep prices down"},
		{"HIDROLISIS", "Reaksi penguraian zat oleh air", "Breaking down a substance with water"},
		{"METAFORA", "Majas perbandingan tanpa kata pembanding", "Figure of speech comparing without like or as"},
		{"VEKTOR", "Besaran yang memiliki nilai dan arah", "Quantity with size and direction"},
		{"FOTON", "Partikel cahaya", "Particle of light"},
		{"GENETIKA", "Ilmu tentang pewarisan sifat", "Science of heredity"},
		{"DESENTRALISASI", "Penyerahan wewenang pusat ke daerah", "Handing central power to regions"},
		{"KOLONIALISME", "Penguasaan suatu bangsa atas wilayah bangsa lain", "One nation ruling another's territory"},
		{"PROBABILITAS", "Peluang terjadinya suatu kejadian", "Chance that an event happens"},
	},
}
