blank_issues_enabled: false
contact_links:
  - name: Security vulnerability report
    url: https://github.com/XCO-Agency/Laravel-SAAS-Starter/security/advisories/new
    about: Please report security issues privately.
