<?php

return [
    /*
    | Games listed on the player portal and dashboard.
    |
    | awards_points: only games whose results are verified server-side (Go game service)
    | may award points. Client-only demos must stay false.
    | guest_playable: must stay false. Every game page requires a signed-in
    | account (routes/web.php auth group); guests are sent to /login.
    | multiplayer: the game uses the standard invite flow (PIN room + link
    | /games/{key}/join/{pin}, see GameInviteController and docs/multiplayer.md).
    | min_players / max_players: people who can play one round, mirroring the Go
    | service limits (services/game/internal/*). Host/projector screens do not count;
    | quiz-duel starts with one player because a bot joins when nobody else waits.
    | released_at: date (Y-m-d, app timezone) the game became playable. /gamelist
    | shows it under "Game terbaru" for PlayerPortal::NEW_GAME_DAYS days.
    */
    'categories' => [
        [
            'key' => 'adventure',
            'titleKey' => 'player.adventure',
            'games' => [
                [
                    'key' => 'flag-quest',
                    'titleKey' => 'player.flagQuest',
                    'descriptionKey' => 'portal.games.flagQuest',
                    'route' => 'games.flag-quest',
                    'icon' => 'flag',
                    'accent' => '#1aab8a',
                    'min_grade' => 1,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 1,
                    'awards_points' => true,
                    'requires_grade' => true,
                    'guest_playable' => false,
                    'released_at' => '2026-10-01',
                ],
            ],
        ],
        [
            'key' => 'board',
            'titleKey' => 'player.board',
            'games' => [
                [
                    'key' => 'snakes-and-ladders',
                    'titleKey' => 'player.snakes',
                    'descriptionKey' => 'portal.games.snakes',
                    'route' => 'games.snakes-and-ladders',
                    'icon' => 'dice',
                    'accent' => '#f5a623',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-09-30',
                ],
            ],
        ],
        [
            'key' => 'quiz',
            'titleKey' => 'player.quiz',
            'games' => [
                [
                    'key' => 'sky-quiz',
                    'titleKey' => 'player.sky',
                    'descriptionKey' => 'portal.games.sky',
                    'route' => 'games.sky-quiz',
                    'icon' => 'plane',
                    'accent' => '#6c5ce7',
                    'min_grade' => 1,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 1,
                    'awards_points' => true,
                    'requires_grade' => true,
                    'guest_playable' => false,
                    'released_at' => '2026-09-30',
                ],
                [
                    'key' => 'quiz-duel',
                    'titleKey' => 'player.duel',
                    'descriptionKey' => 'portal.games.duel',
                    'route' => 'games.quiz-duel',
                    'icon' => 'swords',
                    'accent' => '#ff6584',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 2,
                    'awards_points' => true,
                    'requires_grade' => true,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-04',
                ],
                [
                    'key' => 'floor-drop',
                    'titleKey' => 'player.floorDrop',
                    'descriptionKey' => 'portal.games.floorDrop',
                    'route' => 'games.floor-drop',
                    'icon' => 'layers',
                    'accent' => '#2563eb',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 2,
                    'max_players' => 100,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'economy-heist',
                    'titleKey' => 'player.economyHeist',
                    'descriptionKey' => 'portal.games.economyHeist',
                    'route' => 'games.economy-heist',
                    'icon' => 'vault',
                    'accent' => '#b45309',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 2,
                    'max_players' => 60,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'order-rush',
                    'titleKey' => 'player.orderRush',
                    'descriptionKey' => 'portal.games.orderRush',
                    'route' => 'games.order-rush',
                    'icon' => 'cable',
                    'accent' => '#0f766e',
                    'min_grade' => 10,
                    'max_grade' => 12,
                    'min_players' => 2,
                    'max_players' => 60,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'turbo-trivia',
                    'titleKey' => 'player.turboTrivia',
                    'descriptionKey' => 'portal.games.turboTrivia',
                    'route' => 'games.turbo-trivia',
                    'icon' => 'kart',
                    'accent' => '#e11d48',
                    'min_grade' => 1,
                    'max_grade' => 12,
                    'min_players' => 2,
                    'max_players' => 40,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-06',
                ],
                [
                    'key' => 'block-battle',
                    'titleKey' => 'player.blockBattle',
                    'descriptionKey' => 'portal.games.blockBattle',
                    'route' => 'games.block-battle',
                    'icon' => 'blocks',
                    'accent' => '#ca8a04',
                    'min_grade' => 1,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 50,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-08',
                ],
                [
                    'key' => 'ping-pong',
                    'titleKey' => 'player.pingPong',
                    'descriptionKey' => 'portal.games.pingPong',
                    'route' => 'games.ping-pong',
                    'icon' => 'network',
                    'accent' => '#0f766e',
                    'min_grade' => 1,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 2,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-08',
                ],
                [
                    'key' => 'monster-cafe',
                    'titleKey' => 'player.monsterCafe',
                    'descriptionKey' => 'portal.games.monsterCafe',
                    'route' => 'games.monster-cafe',
                    'icon' => 'chef',
                    'accent' => '#ea580c',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 40,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-08',
                ],
            ],
        ],
        [
            'key' => 'puzzle',
            'titleKey' => 'player.puzzle',
            'games' => [
                [
                    'key' => 'crossword',
                    'titleKey' => 'player.crossword',
                    'descriptionKey' => 'portal.games.crossword',
                    'route' => 'games.crossword',
                    'icon' => 'grid',
                    'accent' => '#0ea5e9',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-04',
                ],
            ],
        ],
        [
            'key' => 'arcade',
            'titleKey' => 'player.arcade',
            'games' => [
                [
                    'key' => 'knowledge-train',
                    'titleKey' => 'player.train',
                    'descriptionKey' => 'portal.games.train',
                    'route' => 'games.knowledge-train',
                    'icon' => 'train',
                    'accent' => '#00c9a7',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 1,
                    'awards_points' => true,
                    'requires_grade' => true,
                    'guest_playable' => false,
                    'released_at' => '2026-10-04',
                ],
                [
                    'key' => 'port-sorter',
                    'titleKey' => 'player.portSorter',
                    'descriptionKey' => 'portal.games.portSorter',
                    'route' => 'games.port-sorter',
                    'icon' => 'network',
                    'accent' => '#0d9488',
                    'min_grade' => 10,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 1,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'snake',
                    'titleKey' => 'player.snake',
                    'descriptionKey' => 'portal.games.snake',
                    'route' => 'games.snake',
                    'icon' => 'gamepad',
                    'accent' => '#10b981',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-30',
                ],
            ],
        ],
        [
            'key' => 'explore',
            'titleKey' => 'player.explore',
            'games' => [
                [
                    'key' => 'market-math',
                    'titleKey' => 'player.marketMath',
                    'descriptionKey' => 'portal.games.marketMath',
                    'route' => 'games.market-math',
                    'icon' => 'cart',
                    'accent' => '#f97316',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'number-garden',
                    'titleKey' => 'player.numberGarden',
                    'descriptionKey' => 'portal.games.numberGarden',
                    'route' => 'games.number-garden',
                    'icon' => 'flower',
                    'accent' => '#22c55e',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'explore-indonesia',
                    'titleKey' => 'player.exploreIndonesia',
                    'descriptionKey' => 'portal.games.exploreIndonesia',
                    'route' => 'games.explore-indonesia',
                    'icon' => 'map',
                    'accent' => '#e11d48',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
                [
                    'key' => 'mini-lab',
                    'titleKey' => 'player.miniLab',
                    'descriptionKey' => 'portal.games.miniLab',
                    'route' => 'games.mini-lab',
                    'icon' => 'flask',
                    'accent' => '#8b5cf6',
                    'min_grade' => 0,
                    'max_grade' => 12,
                    'min_players' => 1,
                    'max_players' => 4,
                    'awards_points' => true,
                    'requires_grade' => false,
                    'guest_playable' => false,
                    'multiplayer' => true,
                    'released_at' => '2026-10-05',
                ],
            ],
        ],
    ],

    /*
    | Points needed per player level on the portal.
    */
    'points_per_level' => 200,
];
